version: "3"
services:
  tunnel-mediator:
    image: dbluhm/agent-tunnel
    command: -s agent-mediator:3004 -p 4040 -h ${AGENT_TUNNEL_HOST}
  agent-mediator:
    image: acapy-toolbox-tunnel
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo
    environment:
      TUNNEL_ENDPOINT: http://tunnel-mediator:4040
    ports:
      - "3005:3005"
    command: start --arg-file ./configs/mediator.yml
