version: "3"
services:
  agent-alice:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./configs:/home/indy/configs:ro,z
    environment:
      ACAPY_ENDPOINT: "[http://${HOST_IP:-localhost}:3000,ws://${HOST_IP:-localhost}:3000]"
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3001:3001"
      - "3000:3000"
    command: start --arg-file ./configs/mediator.yml
    extra_hosts:
      - "localhost:host-gateway"
