version: "3"
services:
  tunnel:
    image: dbluhm/agent-tunnel
    command: -s agent:3000 -p 4040 -h ${AGENT_TUNNEL_HOST}
    ports:
      - 4040:4040
  agent:
    image: acapy-toolbox-tunnel
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo
    environment:
      TUNNEL_ENDPOINT: http://tunnel:4040
