version: "3"
services:

  blab-mediator:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./configs:/home/indy/configs:ro,z
    environment:
      ACAPY_ENDPOINT: "[https://mediator.blabx.online,wss://mediator.blabx.online]"
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3005:3005"
      - "3004:3004"
    command: start --arg-file ./configs/mediator.yml