version: "3"
services:
  agent-alice:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./configs:/home/indy/configs:ro,z
    environment:
      ACAPY_ENDPOINT: "[http://40.76.184.54:3004,ws://40.76.184.54:3004]"
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3005:3005"
      - "3004:3004"
    command: start --arg-file ./configs/mediator.yml
    extra_hosts:
      - "localhost:host-gateway"
