# The mediator has pared down functionality. In order to mediate, only a subset
# of the capabiliteis of other agents is required.

# Load the Plugin
plugin:
    - acapy_plugin_toolbox

# General
label: Blab Mediator
endpoint: https://mediator.blabx.online
inbound-transport:
  - [acapy_plugin_toolbox.http_ws, 0.0.0.0, 3004]
outbound-transport: 
  - http
  - ws

# Mediator does not use ledger
no-ledger: true

# Admin
admin: [0.0.0.0, 3005]
admin-insecure-mode: true

# Connections
debug-connections: true
connections-invite: true
invite-multi-use: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Mediation
open-mediation: true
enable-undelivered-queue: true

# Wallet config
auto-provision: true
recreate-wallet: true
wallet-name: BlabMediatorName
wallet-key: BlabMediatorKey
wallet-type: indy
wallet-storage-type: postgres_storage
wallet-storage-config: "{\"url\":\"40.76.184.54:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}"
wallet-storage-creds: "{\"account\":\"blab\",\"password\":\"blab1234\",\"admin_account\":\"blab\",\"admin_password\":\"blab1234\"}"